### PR TITLE
bugfix: fixup wrong offset storing in interval timer

### PR DESCRIPTION
**Pull request by yangrenyong**
apprantly it seems a bug that the intended offsets are not stored in the timer

### CODE REVIEW

**Comment by zhouxinyu** [comment]
@vesense Could you please help review this PR?

**Comment by vesense** [comment]
@zhouxinyu OK, I will take a look this weekend.

**Comment by vongosling** [comment]
@vesense How is it  going

**Comment by vesense** [comment]
Sorry for the delay.
@yangrenyong The change replaced reduplicate logic by `fetchSubscribeMessageQueues` and that make sense, but it's not a bug. Can you explain more about your question?
> it seems a bug that the intended offsets are not stored in the timer

**Comment by vesense** [comment]
@yangrenyong Any response?
@zhouxinyu @vongosling Although no response from @yangrenyong, we can merge this too. The title of PR should be changed to "MINOR: Replaced reduplicate logic by invoking fetchSubscribeMessageQueues"

**Comment by yangrenyong** [comment]
@vesense sorry for long time not logged in github. The bug lies in line 113 for the version before changed:

 @@ -105,12 +105,7 @@ class MQPullInputDStream(
          new Runnable() {
            def run() {
              try {
 -              val messageQueueSet = new ju.HashSet[MessageQueue]
 -              val iter = topics.iterator
 -              while (iter.hasNext){
 -                  messageQueueSet.addAll(kc.fetchSubscribeMessageQueues(iter.next))
 -              }
 -              kc.getOffsetStore.persistAll(messageQueues)

for the logic in line 113:
 "kc.getOffsetStore.persistAll(messageQueues)"

I think you guys may intend to persist "messageQueueSet", not "messageQueues", am I right?

thx~

**Comment by vesense** [comment]
@yangrenyong You are right. I missed it. Thanks.
+1 for merging.

**Pull request merged**
