### PR TITLE
ROCKETMQ-157: Serializer&Deserializer support for RocketMQ

### PR DESCRIPTION
**Pull request by vesense**
# What is the purpose of the change
RocketMQ-Serializer is a RocketMQ extend library for serializing and deserializing message body.
Both APIs and implements(string, json, avro...) are included in this module.
https://issues.apache.org/jira/browse/ROCKETMQ-157

# Brief changelog
## APIs
The core serializer & deserializer API are interfaces `RocketMQSerializer` and `RocketMQDeserializer`.  
In order to centralized manage avro schemas, you can implement `SchemaRegistry` interface in `rocketmq-serializer-avro` module,
and use `SchemaRegistry` registering and getting schemas.

### Supported Formats

| Format        | Serializer           | Deserializer  |
| ------------- |:-------------:|:------:|
| Raw String      | Y | Y |
| JSON      | Y      |   Y |
| Avro Generic | Y      |    Y |
| Avro Specified | Y      |    Y |

Some serializer performance research please refer to https://github.com/vongosling/jvm-serializer.

### User Defined Formats
You can define your format just implements `RocketMQSerializer` and `RocketMQDeserializer`.

## Tools
`Messages` provides methods like `newMessage` and `getMessageBody` to map between user class and byte array.
`AvroUtils` provides methods `newGenericRecord` and `newSchema` to create avro records and schemas.

## Internals
`rocketmq-serializer-avro` is powered by Apache Avro, and `rocketmq-serializer-json` is powered by fastjson.

# Verifying this change

unit tests check passed ✅ 
apache-rat check passed ✅ 
checkstyle check passed ✅

### CODE REVIEW

**Comment by vesense** [comment]
@vongosling @zhouxinyu Do yo have time to take a look?

**Comment by vesense** [comment]
@vongosling @zhouxinyu ping..

**Comment by vesense** [comment]
Any comments are welcome..

**Comment by vesense** [comment]
Upgraded RocketMQ version to 4.2.0 and removed author infos.
@vongosling @zhouxinyu Can you guys take a look?

**Comment by vongosling** [comment]
Actually, I have trouble fully understanding the project real purpose, do you want to support some serializer for rocketmq send method ?

**Comment by vesense** [comment]
@vongosling This is a tool library for serializing / deserializing message body.
 It provides convenient API for users whatever sending or receiving messages.

**Comment by vesense** [comment]
@vongosling   e.g.
image
image

**Comment by vesense** [comment]
@vongosling Do I make it clear?

**Comment by vongosling** [comment]
yes, I will merge your request, thanks

**Pull request merged**
