### PR TITLE
[ROCKETMQ-293] Add high-availability support for rocketmq-mysql-replicator

### PR DESCRIPTION
**Pull request by zhaoqun911**
### What is the purpose of the change
Add high-availability support for rocketmq-mysql-replicator in order to ensure availability, if a replicator instance crashes, another instance will be started.
JIRA:https://issues.apache.org/jira/browse/ROCKETMQ-293

### Brief change log
* Add HA-mode for rocketmq-mysql-replicator.

### Verifying this change
* Start a zookeeper instance.
* Add the “zkAddr” property in the “rocketmq-mysql.conf” file.
* Start the replicator to verify.

Follow this checklist to help us incorporate your contribution quickly and easily:
- [x] Make sure there is a [JIRA issue](
https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the
change (usually before you start working on it). Trivial changes like typos
do not require a JIRA issue. Your pull request should address just this
issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[ROCKETMQ-XXX] Fix
UnknownException when host config not exist`. Each commit in the pull
request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to
understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock
a little better when cross module dependency exists. If the new feature or
significant change is committed, please remember to add integration-test in
[test module](https://github.com/apache/incubator-rocketmq/tree/master/test
).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs
checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean
install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile
failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual
Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by zhouxinyu** [comment]
LGTM, is this PR ready to merge? @zhaoqun911

**Comment by zhaoqun911** [comment]
@zhouxinyu Yes,please merge it,thanks.

**Comment by vongosling** [comment]
I will merge it tomorrow :-)

**Comment by vongosling** [comment]
@zhaoqun911 thanks, I have merged it.

**Pull request merged**
