### PR TITLE
[ROCKETMQ-193] Develop rocketmq-redis-replicator component

### PR DESCRIPTION
**Pull request by leonchen83**
### What is the purpose of the change  

Develop sub-project rocketmq-redis-replicator   
JIRA: [https://issues.apache.org/jira/browse/ROCKETMQ-193](https://issues.apache.org/jira/browse/ROCKETMQ-193).  

### Brief change log

add sub-project rocketmq-redis-replicator   

### Verifying this change

execute `mvn clean package` to verify.  

Follow this checklist to help us incorporate your contribution quickly and easily:  

- [x] Make sure there is a JIRA issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.  
- [x] Format the pull request title like [ROCKETMQ-XXX] Fix UnknownException when host config not exist. Each commit in the pull request should have a meaningful subject line and body.  
- [x] Write a pull request description that is detailed enough to understand the pull request :
    *  What is the purpose of the change  
    *  Brief change log
    *  Verifying this change  
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in test module.  
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test` to make sure integration-test pass.  
- [x] If this contribution is large, please file an Apache Individual Contributor License Agreement.

### CODE REVIEW

**Comment by leonchen83** [comment]
@Zhang-Ke 
@vongosling

**Comment by vongosling** [comment]
@leonchen83 Thanks for your contribution. BTW, have you test it in your local environment ?

**Comment by leonchen83** [comment]
I can finish full test case this weekend. 
For now I only test replicate from redis . but not test data stream to RocketMQ.

**Comment by vongosling** [comment]
Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ]  Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/ROCKETMQ/issues/) filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ROCKETMQ-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-rocketmq/tree/master/test).
- [ ]  Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ]  If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

**Comment by vongosling** [comment]
Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in test module.


Do you have test module in this replicator ?

**Comment by leonchen83** [comment]
any reference or example for step 4 ? 
@vongosling

**Comment by vongosling** [comment]
Consider this is the first commit for this project, I would like to recommend creating one module naming test for integration test :-)

**Comment by leonchen83** [comment]
I recommend using travis ci to do integration test as other open source project.
but first need to add this sub-project to travis ci.
I have no permission to do this.

**Comment by leonchen83** [comment]
@vongosling I already added an integration-test to rocketmq-redis-replicator base on travis-ci.
please help review this commit

**Comment by leonchen83** [comment]
@vongosling you will see the result of integration-test at [incubator-rocketmq-externals](https://travis-ci.org/leonchen83/incubator-rocketmq-externals/branches)

**Comment by zhouxinyu** [comment]
Hi, @leonchen83 don't forget to submit the [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas), since this is a large PR.

**Comment by zhouxinyu** [comment]
And we need a detailed README to quick start with the projects~ 😄

**Comment by leonchen83** [comment]
@zhouxinyu ICLA already signed

**Comment by leonchen83** [comment]
@zhouxinyu README.md added

**Comment by vongosling** [comment]
@leonchen83 Could you show us the ICLA you have already signed, I will try to merge your first PR

**Comment by leonchen83** [comment]
@vongosling 
mailed to vongosling@apache.org

**Comment by vongosling** [comment]
@leonchen83 thanks for your Redis contribution, I have merged. What is the next plan ? Could you introduce some success use case for this project?

**Pull request merged**
