### PR TITLE
[ROCKETMQ-282]RocketMQ-GO-Client

### PR DESCRIPTION
**Pull request by StyleTang**
[ROCKETMQ-282 RocketMQ-GO-Client](https://issues.apache.org/jira/browse/ROCKETMQ-282)
[Document](https://github.com/StyleTang/incubator-rocketmq-externals/blob/master/rocketmq-go/README.md)
Please review.
Your advice will help us improve it.
:-)

### CODE REVIEW

**Comment by zhouxinyu** [comment]
cool~ 
Thanks @StyleTang

**Comment by zjykzk** [comment]
come on!

**Comment by lindzh** [comment]
Thanks for contributing.It's very pleased to see such a big change for RocketMQ client family.
In the next,I expect the test case to be more complete.

**Comment by zhiw2019** [comment]
go语言的client，有时间计划吗，什么时候能发布功能完整的版本？

**Comment by vongosling** [comment]
How the things going on, guys

**Comment by vongosling** [comment]
@StyleTang ping ...

**Comment by vongosling** [comment]
@StyleTang ping again

**Comment by wenfengwang** [comment]
I want continue this work，does anyone have a suggestion?

**Comment by vongosling** [comment]
@StyleTang @wenfengwang could we discuss the milestone together, how do you plan to finish it ? I would like to help you finish it.

**Comment by wenfengwang** [comment]
@vongosling ok, i also think the milestone or a road map is necessary,  we can disscuss on wechat or qq if possiable, mail is also ok.  because codebase of go is based on v4.1.0, so have any big update were added to client in past year?

**Pull request merged**
