### PR TITLE
docker-compose script has been added for 4.1.0-incubating

### PR DESCRIPTION
**Pull request by theocat**

### CODE REVIEW

**Comment by zhouxinyu** [comment]
Hi, sorry for late, it seems that there are some scripts still use `4.0.0-incubating` version?

**Comment by theocat** [comment]
@zhouxinyu I'll update the PR

**Comment by theocat** [comment]
@zhouxinyu done

**Comment by vongosling** [comment]
@dongeforever Could you help to review it :-)

**Pull request merged**
