### PR TITLE
Enhance consumer classes so that consumer classes can be inherited

### LINKED ISSUE #173: spring-boot-starter consumers cannot be inherited
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

I want to define an abstract class that inherits RocketMQListener, which is used to handle message acceptance and message forwarding. When inheriting this abstract class as a consumer, the message will be reported incorrectly.

- What did you expect to see?

Classes that implement RocketMQListener can be inherited and can accept messages as consumers.

- What did you see instead?

The consuers can‘t receive message and throw a exception

 2018-12-05 01:26:23.401  INFO 2653 --- [MessageThread_1] r.s.s.s.DefaultRocketMQListenerContainer : convert failed. str:broadcast msg, msgType:class java.lang.Object
2018-12-05 01:26:23.409  WARN 2653 --- [MessageThread_1] r.s.s.s.DefaultRocketMQListenerContainer : consume message failed. messageExt:MessageExt [queueId=2, storeSize=282, queueOffset=4, sysFlag=0, bornTimestamp=1543944383229, bornHost=/192.168.0.13:38042, storeTimestamp=1543944383230, storeHost=/172.17.0.1:10911, msgId=AC11000100002A9F000000000002C7C0, commitLogOffset=182208, bodyCRC=278141710, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='broadcastTopic-topic', flag=0, properties={USERS_id=3e3fdc75-55a7-9dee-e6c3-a21e8de05d1f, MIN_OFFSET=0, USERS_timestamp=1543944383227, MAX_OFFSET=5, USERS_contentType=text/plain, CONSUME_START_TIME=1543944383399, UNIQ_KEY=AC1100010B0518B4AAC214E886FD000F, WAIT=false}, body=[98, 114, 111, 97, 100, 99, 97, 115, 116, 32, 109, 115, 103], transactionId='null'}]

java.lang.RuntimeException: cannot convert message to class java.lang.Object
	at org.apache.rocketmq.spring.starter.supports.DefaultRocketMQListenerContainer.doConvertMessage(DefaultRocketMQListenerContainer.java:222) ~[classes/:na]
	at org.apache.rocketmq.spring.starter.supports.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:50) ~[classes/:na]
	at org.apache.rocketmq.spring.starter.supports.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:154) ~[classes/:na]
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:417) [rocketmq-client-4.3.0.jar:4.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'broadcast': was expecting ('true', 'false' or 'null')
 at [Source: broadcast msg; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858) ~[jackson-databind-2.8.10.jar:2.8.10]
	at org.apache.rocketmq.spring.starter.supports.DefaultRocketMQListenerContainer.doConvertMessage(DefaultRocketMQListenerContainer.java:219) ~[classes/:na]
	... 9 common frames omitted

2. Please tell us about your environment:

jdk1.8
ubuntu 18.4

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

### PR DESCRIPTION
**Pull request by odbozhou**
Fixed #173  spring-boot-starter consumers cannot be inherited 

## What is the purpose of the change

Enhance consumer classes so that consumer classes can be inherited

## Brief changelog

Look for the RocketMQListener interface from the current class, if not found then look up from the parent class until it is found

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by vongosling** [comment]
@odbozhou Could you help to provide some test for the pr.

**Comment by vongosling** [comment]
@odbozhou Could you please fix the conflict and add some test, we will release the 2.0.0 version recently, glad to see your pr merged.

**Comment by odbozhou** [comment]
> 
> 
> @odbozhou Could you please fix the conflict and add some test, we will release the 2.0.0 version recently, glad to see your pr merged.

@vongosling  I've fixed the conflict and provided some simple unit tests

**Comment by odbozhou** [comment]
@vongosling hi， RocketMQ Spring already has a separate repository. Should I close this pr and resubmit the new pr to RocketMQ Spring's new repository？

**Comment by vongosling** [comment]
@odbozhou Thanks for your active followup with the project. Once the issue and pr are open for the new repository, I will inform you :-)

**Comment by vongosling** [comment]
@odbozhou https://github.com/apache/rocketmq-spring/pulls, pr function has opened

**Pull request closed without merging**
