### PR TITLE
[ISSUE #614] redirect too many times after enable user login

### PR DESCRIPTION
**Pull request by imaffe**
## What is the purpose of the change

1. fix the bug described in ISSUE #614 
2. restrict access to protected resources

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by iyuq** [comment]
这样改会不会好一点：`registry.addInterceptor(authInterceptor).excludePathPatterns("/error", "/user/guide/**", "/", "/**/*.js", "/**/*.html", "/**/*.json", "/**/*.css", "/login/**");`

**Comment by iyuq** [comment]
@imaffe

**Comment by iyuq** [comment]
之后其他路径增加了css和js还有html都不需要修改配置了

**Comment by imaffe** [comment]
> 之后其他路径增加了css和js还有html都不需要修改配置了

I don't know what should be protected, like for "including style" we only protect data-related api so all css/html/js files are not protected. However for excluding style, if we have other types of static resources, we need to change the configs here. I'm ok with both solution~

**Comment by iyuq** [comment]
Spring 的 path pattern 不支持真正的正则表达式，所以写后缀确实也会比较麻烦

**Comment by imaffe** [comment]
> Spring 的 path pattern 不支持真正的正则表达式，所以写后缀确实也会比较麻烦

Though your proposal is more aligned with least privilege principle, and this is basically

1. default no access, allow access on certain resources 
versus
2. default all access,  deny access on certain resources. 

If using method 1, I don't know if I can enumerate all resources that needs be accessed without protection as I believe in this scenario "public resources" are more than "need-protect resources". 

I agree with both way but I think method 2 are probably easier to maintain as we know what API exposes data.

**Pull request merged**
