### PR TITLE
Fix trace 

### PR DESCRIPTION
**Pull request by ahuazhu**
## What is the purpose of the change

Fix [ISSUE #235 ](https://github.com/apache/rocketmq-externals/issues/235)

Fixed rocketmq-client with pull request 

## Brief changelog

* For SubBefore show the client IP and brokerName:queueId
* For SubAfter show client IP

https://github.com/apache/rocketmq/pull/1121

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by walking98** [comment]
LGTM

**Comment by zongtanghu** [comment]
@ahuazhu  Can I join you in dingding talk or WeChat？I find your pr is the same as other people's.

**Comment by zongtanghu** [comment]
LGTM

**Comment by yongliangcode** [comment]
Hi, 

The RocketMQ message track contains the IP not yet merged, and is now in the review phase.
I recommend using the decoderFromTraceDataString method in org.apache.rocketmq.client.trace.TraceDataEncoder.java to parse the message.

**Comment by vongosling** [comment]
@zongtanghu @ahuazhu any update？

**Comment by ahuazhu** [comment]
@vongosling @zongtanghu 

The problem may be a bit more complicated than expected. Compatibility has not been noticed in this PR.
Please look at the code below (from `org.apache.rocketmq.console.util.MsgTraceDecodeUtil#decoderFromTraceDataString(String)`)
 
```
if (line[0].equals(Pub.name())) {
   ...
                if (line.length == 13) {
                    pubContext.setSuccess(Boolean.parseBoolean(line[12]));
                } else if (line.length == 14) {
                    bean.setOffsetMsgId(line[12]);
                    pubContext.setSuccess(Boolean.parseBoolean(line[13]));
                }
   ...
}
```

Thus limit the ability to extend fields of Pub. If we add new fields to the Pub lines, the console of the older versions will lose the information about _isSuccess_ and _offsetMsgId_. 

1. Require users to upgrade the console to the newer version may be a straightforward solution. And follow the paradigm of `if(line.length >= n)` to keep the extensibility in future.

2. Alternatively, we could introduce another _TraceType_ name, such as _PubNew_. We reserve the  _Pub_ in the trace message and mark @Deprecated to keep compatibility.  And encode the new information to the _PubNew_ lines. For transfer and storage consideration, we could reuse the data in the _Pub_ lines to reduce the bytes of TraceMessage in the latest console.  For example:

```
Pub_${timestamp}_${regionid}_ ...
PubNew_${Pub_IP}_...
```
We combine the two line in the console to get all information about produce trace. Finally, _Pub_ lines would be removed. 

3. A more radical approach is re-define the format of the trace messages to maintain the extensibility. The KV-liked format like JSON provides sufficient extensibility in this scene. JSON consume too many bytes, but we could reduce it by encoding the keys to sequences, and remove all quotations. For example, define all the keys in a class like 

```
class TraceKeys {
    final String timestamp = "0";
    final String regionId = "1";
    final String pubIp = "a";
}
```
Thus the prouduce message would be encoded like

```
Pub:=1:123,a:10.10.10.10,1:1561608845
``` 
which means regionId is 123, pubIp is 10.10.10.1 and the timestamp is 1561608845.
This way console will not need to count the field's index.

**Pull request closed without merging**
