### PR TITLE
[ROCKETMQ-297] Support windows platform for rocketmq-cpp code

### PR DESCRIPTION
**Pull request by vincentWangKB**
support both windows and linux platform

### CODE REVIEW

**Comment by lzk90s** [comment]
windows下打印日志使用%zd的地方，会导致崩溃

**Comment by lzk90s** [comment]
还有貌似日志ALOG_ADAPTER得先初始化，使用的时候再初始化，boost中会概率崩溃，把日志放在DefaultMQPushConsumer::DefaultMQPushConsumer最开始，就没有出现过崩溃

**Comment by lzk90s** [comment]
刷新订阅的时候，订阅的tag不会变，
如：
subscirbe("TOPIC", "*");
subscribe("TOPIC", "A || B");
刷新订阅后tag没有变化

**Comment by lizhanhui** [comment]
@vincentWangKB Could please help resolve conflicts?

**Comment by vincentWangKB** [comment]
@lzk90s subscribe will be valid only if it was set before consumer start

**Comment by vincentWangKB** [comment]
@lzk90s logInstance concurrency create issue and windows size_t print issue are resolved, please retry again, thanks your advise

**Comment by lzk90s** [comment]
你好，windows下有一个bug
具体原因如下：
-------------------------------
在LocalFileOffsetStore::LocalFileOffsetStore()接口中，使用了UtilAll::getLocalAddress()来组装offset的保存路径。UtilAll::getLocalAddress() 可能获取到IPV6地址，比如fe80::bc6e:cb4:5f6e:1448%11 这样的。IPV6地址中存在冒号：这个特殊符号，windows不支持冒号：这个特殊符号，会导致创建目录会失败

LocalFileOffsetStore::LocalFileOffsetStore(const string& groupName,
                                           MQClientFactory* pfactory)
    : OffsetStore(groupName, pfactory) {
  MQConsumer* pConsumer = pfactory->selectConsumer(groupName);
  if (pConsumer) {
    LOG_INFO("new LocalFileOffsetStore");
    string directoryName =
        UtilAll::getLocalAddress() + "@" + pConsumer->getInstanceName();
    m_storePath = ".rocketmq_offsets/" + directoryName + "/" + groupName;
    string homeDir(UtilAll::getHomeDirectory());
    m_storeFile = homeDir + "/" + m_storePath + "/offsets.Json";
  }
}

**Comment by vincentWangKB** [comment]
@lzk90s I will check it later.

**Comment by vongosling** [comment]
@vincentWangKB I have merged this pr, thanks. If you have any polish, please let me see :-)

**Pull request closed without merging**
