### PR TITLE
ISSUE-57: Some improvements for RocketMQ-Spark

### PR DESCRIPTION
**Pull request by vesense**
## What is the purpose of the change
Issue: https://github.com/apache/rocketmq-externals/issues/57
Given some improvements for RocketMQ-Spark.

## Brief changelog

* Upgraded RocketMQ version to 4.2.0
* Removed duplicated gitignore
* Removed author infos
* Enabled unit tests by default
* Removed the dependency of java class refer to scala `RocketMqUtils`
* Moved `RocketMqRDD` and `MQPullInputDStream` to the right directory. These two class should be in the `org.apache.spark` package due to the limit of being invoked APIs `private[spark]`.
* Some minor code style and documents improvements

## Verifying this change

unit tests check passed ✅ 
apache-rat check passed ✅ 
checkstyle check passed ✅ 

  

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [ ] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by vesense** [comment]
@vongosling @zhouxinyu Do yo have time to take a look?

**Comment by vongosling** [comment]
Got it, please no hurry up, I will check it these days.

**Comment by vesense** [comment]
@vongosling OK. Thanks.

**Comment by vongosling** [comment]
I would like to merge the PR, thanks @vesense

**Pull request merged**
