### PR TITLE
[Issue #770] [RocketMQ Console] Send message with message trace

### PR DESCRIPTION
**Pull request by StyleTang**
## What is the purpose of the change

Send test message with message trace

## Brief changelog

User can choose send test message with message trace or not.

### Send test message with trace on.
image

### Message Trace
image

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by weibubli** [comment]
LGTM

**Comment by vongosling** [comment]
@StyleTang Could you help to check again, the code has a conflict with the latest update for SSL:-)

**Comment by StyleTang** [comment]
Conflict resolved.

**Comment by zhangjidi2016** [comment]
LGTM

**Comment by vongosling** [comment]
There are too many errors in our unit test, I think this is a very good contribution spot, looking forward to your attention here :-) @weibubli @zhangjidi2016 @StyleTang

**Comment by zhangjidi2016** [comment]
Most of the errors were thrown by the previous XxxServiceImpl unit test, and the execution time was very long, I think we can delete this section, the submitted controller unit test has basically covered XxxServiceImpl in the execution.
This is the unit test time I executed after I removed xxxServiceImplTest and the overall project code coverage.

image
image

**Comment by vongosling** [comment]
@zhangjidi2016 cool, I like what you said. could you pr it and I'd like to help to check it again?

**Comment by zhangjidi2016** [comment]
> @zhangjidi2016 cool, I like what you said. could you pr it and I'd like to help to check it again?

[https://github.com/apache/rocketmq-externals/pull/774](url) @vongosling

**Pull request merged**
